/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as RoomsRouteImport } from './routes/rooms';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as NotificationsRouteImport } from './routes/notifications';
import { Route as MyMeetingsRouteImport } from './routes/my-meetings';
import { Route as InvitationsRouteImport } from './routes/invitations';
import { Route as ChangePasswordRouteImport } from './routes/change-password';
import { Route as CalendarRouteImport } from './routes/calendar';
import { Route as IndexRouteImport } from './routes/index';
const RoomsRoute = RoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const NotificationsRoute = NotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => rootRouteImport,
});
const MyMeetingsRoute = MyMeetingsRouteImport.update({
    id: '/my-meetings',
    path: '/my-meetings',
    getParentRoute: () => rootRouteImport,
});
const InvitationsRoute = InvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => rootRouteImport,
});
const ChangePasswordRoute = ChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => rootRouteImport,
});
const CalendarRoute = CalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    CalendarRoute: CalendarRoute,
    ChangePasswordRoute: ChangePasswordRoute,
    InvitationsRoute: InvitationsRoute,
    MyMeetingsRoute: MyMeetingsRoute,
    NotificationsRoute: NotificationsRoute,
    ProfileRoute: ProfileRoute,
    RoomsRoute: RoomsRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
